server:
  port: 10016

spring:
  application:
    name: study-gateway
  #配置nacos注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true #默认为false 设置true可以通过开启微服务创建路由功能，即可以通过微服务名称访问服务

      enabled: true #是否开启网关功能
