server:
  port: 10004

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: spring-cloud-dubbo-server

dubbo:
  scan:
    base-packages: com.zzh.dream
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
