server:
  port: 10018
spring:
  application:
    name: seata-inventory
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: my_test_tx_group
        registry:
          # 指定nacos作为注册中心
          type: nacos
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: ""
            group: SEATA_GROUP
        config:
          # 指定nacos作为配置中心
          type: nacos
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: "54433b62-df64-40f1-9527-c907219fc17f"
            group: SEATA_GROUP

 #集成Mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/zzh_test?characterEncoding=utf-8
    username: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  basePackage: com.zzh.dream.seataorder.mapper

logging:
  level:
    root: DEBUG




