
server:
  port: 20002
  servlet:
    context-path: /order

spring:
  application:
    name: zzh-cloud-goods
  #配置nacos注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848



