server:
  port: 20002
  servlet:
    context-path: /zzh-order

spring:
  application:
    name: zzh-cloud-order
  #配置nacos注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      #配置nacos配置中心的地址
      config:
        server-addr: 127.0.0.1:8848

    # 添加sentinel的控制台地址 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer port: 8719
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        #应用本地会起一个该端口占用的HttpServer port: 8719
        port: 8719
      #启动立即加载初始化, 而不是有流量之后再和控制台交互
      eager: true

    # seata 配置
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应
        tx-service-group: my_test_tx_group
        registry:
          #指定nacos作为注册中心
          type: nacos
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: ""
            group: SEATA_GROUP
        config:
          type: nacos
          nacos:
            server-addr: 127.0.0.1:8848
            namespace: "54433b62-df64-40f1-9527-c907219fc17f"
            group: SEATA_GROUP


  #redis配置
  redis:
    host: localhost
    password:
    port: 6379

  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/zzh_test?characterEncoding=utf-8&useSSL=true
    username: root

#Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  basePackage: com.zzh.cloud.mapper

#日志配置
logging:
  level:
    root: info
    org:
      springframework:
        core: info
        web: info
      mybatis: info

#sentinel暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

#开启sentinel对feign的支持
feign:
  sentinel:
    enabled: true








