server:
  port: 20001
  servlet:
    context-path: /zzh-goods

spring:
  application:
    name: zzh-cloud-goods
  #配置nacos注册中心的地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #集成Mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/zzh_test?characterEncoding=utf-8&useSSL=true
    username: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
  basePackage: com.zzh.dream.seataorder.mapper


logging:
  level:
    root: info
    org:
      springframework:
        core: info
        web: info
      mybatis: info






